language: rust
services:
  - docker

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - name: clippy & fmt
      rust: stable
      before_install:
        - rustup component add rustfmt clippy
      install:
        - wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz;
          tar -xf go1.14.1.linux-amd64.tar.gz -C $HOME;
          export PATH="$HOME/go/bin:$PATH";
          export GOROOT=$HOME/go;
      script:
        - cargo clippy --all-features -- -D warnings
        - cargo fmt -- --check
    - name: Dgraph 1.0 tests
      rust: stable
      before_install:
        - docker-compose -f docker-compose-1-0.yaml up -d
        - docker ps
      install:
        - wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz;
          tar -xf go1.14.1.linux-amd64.tar.gz -C $HOME;
          export PATH="$HOME/go/bin:$PATH";
          export GOROOT=$HOME/go;
      script:
        - cargo test --verbose -- --test-threads=1
    - name: Dgraph 1.1 tests
      rust: stable
      before_install:
        - docker-compose -f docker-compose-1-1.yaml up -d
        - docker ps
      install:
        - wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz;
          tar -xf go1.14.1.linux-amd64.tar.gz -C $HOME;
          export PATH="$HOME/go/bin:$PATH";
          export GOROOT=$HOME/go;
      script:
        - cargo test --no-default-features --features dgraph-1-1 --verbose -- --test-threads=1
    - name: Dgraph 1.2 tests
      rust: stable
      before_install:
        - docker-compose -f docker-compose-1-2.yaml up -d
        - docker ps
      install:
        - wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz;
          tar -xf go1.14.1.linux-amd64.tar.gz -C $HOME;
          export PATH="$HOME/go/bin:$PATH";
          export GOROOT=$HOME/go;
      script:
        - cargo test --no-default-features --features dgraph-1-1 --verbose -- --test-threads=1
